apiVersion: v1
kind: Namespace
metadata:
  name: juice-shop
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: juice-shop-sa
  namespace: juice-shop
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: juice-shop-deployment
  namespace: juice-shop
  labels:
    app: juice-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: juice-shop
  template:
    metadata:
      labels:
        app: juice-shop
    spec:
      serviceAccountName: juice-shop-sa
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: juice-shop
        # checkov:skip=CKV_K8S_14: "Risk Accepted: Using latest tag for lab"
        # checkov:skip=CKV_K8S_43: "Risk Accepted: Image digest not required for lab"
        # checkov:skip=CKV_K8S_22: "Risk Accepted: Writable filesystem for SQLite"
        # checkov:skip=CKV_K8S_21: "Risk Accepted: Lab environment usage"
        image: bkimminich/juice-shop:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "500m"
            memory: "256Mi"
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: juice-shop-service
  namespace: juice-shop
spec:
  selector:
    app: juice-shop
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
