name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  security-scan:
    name: Checkov SAST Scan
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 
      - name: Run Checkov Security Scan
        run: checkov -d . --output json > checkov-report.json
      - name: Upload Checkov Report
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808
        if: always()
        with:
          name: checkov-scan-report
          path: checkov-report.json

  infrastructure-deploy:
    name: Terraform Apply (LocalStack)
    runs-on: self-hosted
    needs: security-scan
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Terraform Init
        run: terraform init
      - name: Terraform Apply
        run: terraform apply -auto-approve

  container-security:
    name: Trivy Container Scan
    runs-on: self-hosted
    needs: infrastructure-deploy
    steps:
      - name: Pull Juice Shop Image
        run: docker pull bkimminich/juice-shop:latest
      - name: Run Trivy Vulnerability Scanner
        run: trivy image --format json --output trivy-report.json --severity HIGH,CRITICAL --exit-code 0 bkimminich/juice-shop:latest
      - name: Upload Trivy Report
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808
        if: always()
        with:
          name: trivy-scan-report
          path: trivy-report.json

  app-deploy:
    name: Deploy to Kubernetes
    runs-on: self-hosted
    needs: container-security
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Deploy Juice Shop to Kind Cluster
        run: kubectl apply -f k8s/juice-shop.yaml

  # LE GRAND FINAL : OWASP ZAP (DAST)
  dast-scan:
    name: OWASP ZAP DAST Attack
    runs-on: self-hosted
    needs: app-deploy
    steps:
      - name: Wait for App to start
        run: kubectl wait --for=condition=available --timeout=120s deployment/juice-shop-deployment
      
      - name: Port Forward K8s Service (Open the door)
        run: |
          kubectl port-forward service/juice-shop-service 3000:3000 &
          sleep 10
          
      - name: Run ZAP Baseline Attack
        # Attaque l'application en cours d'exécution et génère un rapport HTML
        run: docker run --rm -v $(pwd):/zap/wrk/:rw --net=host ghcr.io/zaproxy/zaproxy:stable zap-baseline.py -t http://localhost:3000 -I -r zap-report.html
        
      - name: Upload ZAP Report
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808
        if: always()
        with:
          name: zap-scan-report
          path: zap-report.html
