name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  security-scan:
    name: Checkov SAST Scan
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 

      - name: Run Checkov Security Scan
        run: checkov -d . --output json > checkov-report.json

      - name: Upload Checkov Report
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808
        if: always()
        with:
          name: checkov-scan-report
          path: checkov-report.json

  infrastructure-deploy:
    name: Terraform Apply (LocalStack)
    runs-on: self-hosted
    needs: security-scan
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Terraform Init
        run: terraform init
      - name: Terraform Apply
        run: terraform apply -auto-approve

  container-security:
    name: Trivy Container Scan
    runs-on: self-hosted
    needs: infrastructure-deploy
    steps:
      - name: Pull Juice Shop Image
        run: docker pull bkimminich/juice-shop:latest
      
      - name: Run Trivy Vulnerability Scanner
        run: trivy image --format json --output trivy-report.json --severity HIGH,CRITICAL --exit-code 0 bkimminich/juice-shop:latest

      - name: Upload Trivy Report
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808
        if: always()
        with:
          name: trivy-scan-report
          path: trivy-report.json

  app-deploy:
    name: Deploy to Kubernetes
    runs-on: self-hosted
    needs: container-security
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        
      - name: Deploy Juice Shop to Kind Cluster
        run: kubectl apply -f k8s/juice-shop.yaml
